In [2]:
# 1. Applying the random Forest Regressor on the ames dataset

from sklearn.datasets import fetch_openml
ames = fetch_openml(name = 'house_prices' , as_frame = True)
df = ames.frame
df = df.copy()

In [3]:
df.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [4]:
#1. selecting the collumns
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [5]:
columns = [
    "OverallQual",
    "OverallCond",
    "GrLivArea",
    "CentralAir",
    "TotalBsmtSF",
    "SalePrice",
]

df = df[columns]
df.head()

   OverallQual  OverallCond  GrLivArea CentralAir  TotalBsmtSF  SalePrice
0            7            5       1710          Y          856     208500
1            6            8       1262          Y         1262     181500
2            7            5       1786          Y          920     223500
3            7            5       1717          Y          756     140000
4            8            5       2198          Y         1145     250000

In [6]:
# 1. mapping the Y and N
df['CentralAir'] = df['CentralAir'].map({'N': 0, 'Y': 1})
df['CentralAir'].value_counts()

CentralAir
1    1365
0      95
Name: count, dtype: int64

In [7]:
df.isnull().sum()

OverallQual    0
OverallCond    0
GrLivArea      0
CentralAir     0
TotalBsmtSF    0
SalePrice      0
dtype: int64

CREATING THE Random forrest Regressor

In [10]:
# 1. selecting the data
target = 'SalePrice'
features = df.columns[df.columns != target]

print(target)
print(features)

SalePrice
Index(['OverallQual', 'OverallCond', 'GrLivArea', 'CentralAir', 'TotalBsmtSF'], dtype='object')

In [11]:
X = df[features].values
y = df[target].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size = 0.3,
                                                    random_state = 42)


# 1. creating the RandomforestRegressor
from sklearn.ensemble import RandomForestRegressor

forest = RandomForestRegressor(n_estimators=100,
                               criterion='squared_error',
                               random_state= 42,
                               n_jobs = -1)

#2. fitting the data to the Algo
forest.fit(X_train , y_train)
y_train_pred = forest.predict(X_train)
y_test_pred = forest.predict(X_test)


# 3. finding the Eroor
from sklearn.metrics import mean_absolute_error , r2_score
mae_train = mean_absolute_error(y_train, y_train_pred)
mae_test = mean_absolute_error(y_test, y_test_pred)

print(f'MAE Train: {mae_train:.2f}')
print(f'MAE Test: {mae_test:.2f}')
print("-"*50)
print(f'R2 Score Train: {r2_score(y_train, y_train_pred):.2f}')
print(f'R2 Score Test: {r2_score(y_test, y_test_pred):.2f}')

MAE Train: 9146.57
MAE Test: 19680.57
--------------------------------------------------
R2 Score Train: 0.96
R2 Score Test: 0.87